on: [push]

jobs:
  generate_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: work-in-progress gif
        uses: rocktimsaikia/action-wippy@v2.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
