on: [push]

jobs:
  generate_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add a wip gif
        uses: rocktimsaikia/action-wippy@v1
        with:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
